//! `SeaORM` Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "matchmaking_player_invitation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub invited_player: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub invitation: Uuid,
    pub expires_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
}


impl ActiveModelBehavior for ActiveModel {}
