//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "matchmaking_player_invitation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub invited_player: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub invitation: Uuid,
    pub expires_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::matchmaking_invitation::Entity",
        from = "Column::Invitation",
        to = "super::matchmaking_invitation::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MatchmakingInvitation,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::InvitedPlayer",
        to = "super::users::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::matchmaking_invitation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MatchmakingInvitation.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
