//! `SeaORM` Entity. Generated by sea-orm-codegen 0.6.0

use super::sea_orm_active_enums::LobbyPrivacy;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use twilight_model::id::marker::{ChannelMarker, MessageMarker};

use crate::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "matchmaking_lobbies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub started_at: DateTimeUtc,
    pub timeout_after: DateTimeUtc,
    pub ended_at: Option<DateTimeUtc>,
    pub channel_id: IdWrapper<ChannelMarker>,
    pub description: Option<String>,
    pub owner: Uuid,
    #[sea_orm(default_value = LobbyPrivacy::Open)]
    pub privacy: LobbyPrivacy,
    pub game: Option<Uuid>,
    pub game_other: Option<String>,
    pub timeout_warning_message: Option<IdWrapper<MessageMarker>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        has_one = "super::game::Entity",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Game,
    #[sea_orm(
        has_one = "super::users::Entity",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    Owner,
    #[sea_orm(has_many = "super::matchmaking_player_lobby::Entity")]
    MatchmakingPlayerLobby,
    #[sea_orm(
        belongs_to = "super::matchmaking_invitation::Entity",
        from = "Column::Id",
        to = "super::matchmaking_invitation::Column::Lobby",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    Invitations,
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Owner.def()
    }
}

impl Related<super::matchmaking_player_lobby::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MatchmakingPlayerLobby.def()
    }
}

impl Related<super::matchmaking_invitation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invitations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
