//! `SeaORM` Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use twilight_model::id::marker::{ChannelMarker, MessageMarker};

use crate::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "matchmaking_invitation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(nullable)]
    pub lobby: Option<Uuid>,
    /// The user being invited.
    pub extended_to: Uuid,
    /// The user who sent the invitation.
    pub invited_by: Uuid,
    pub game: Option<Uuid>,
    pub description: Option<String>,
    /// The ID of the channel that the Discord Message is in
    pub channel_id: IdWrapper<ChannelMarker>,
    /// The ID of the Discord message.
    pub message_id: Option<IdWrapper<MessageMarker>>,
    pub expires_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::game::Entity",
        from = "Column::Game",
        to = "super::game::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Game,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::InvitedBy",
        to = "super::users::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    InvitedBy,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ExtendedTo",
        to = "super::users::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ExtendedTo,
    #[sea_orm(
        belongs_to = "super::matchmaking_lobbies::Entity",
        from = "Column::Lobby",
        to = "super::matchmaking_lobbies::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Lobby,
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InvitedBy.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
