//! `SeaORM` Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;
use sea_orm::sea_query;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Iden,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "lobby_privacy")]
pub enum LobbyPrivacy {
    #[sea_orm(string_value = "invite_only")]
    InviteOnly,
    #[sea_orm(string_value = "open")]
    Open,
}
